### ISSUE TITLE
图像编码器配置

### ISSUE THREAD

**Issue by yuyq96** [X-PLUG/mPLUG-DocOwl#1]
请问图像编码器使用多大的图像输入，patch size是多少呢？
如果按照mPLUG-Owl的配置，ViT-L14在224x224分辨率上能够分辨样例中的密集文字吗？比如document和webpage

**Comment by LukeForeverYoung** [comment]
We develop an algorithm to extend the frozen VisionTransformer to handle high resolution input images (i.e., 896*896) without model modifications. This is our ongoing research work, and we will open source the code and update the technical report in the future. Stay tuned ^_^.
