### ISSUE TITLE
Clarification on Architecture Components in mPLUG-DOCOWL2

### ISSUE THREAD

**Issue by FeliceSchena** [X-PLUG/mPLUG-DocOwl#112]
Hi, thanks for your effort in making the new mPLUG-DOCOWL2 open source. I'm currently trying to understand how it works. Referring to the image below, Section 3 states that there is a low-resolution vision encoder and an H-reducer. However, I can't find either of those components in the image, or they aren't depicted clearly. Could someone clarify the overall architecture? Apologies if this is a basic question!

![image](https://github.com/user-attachments/assets/defc2ef1-0ca5-42ce-b49a-e91e70741827)

**Comment by HAWLYQ** [comment]
Hi, @FeliceSchena , the low-resolution vision encoder and the HReducer are included in the High-resolution Visual Encoding module in this figure~
