### ISSUE TITLE
demo space is down

### ISSUE THREAD

**Issue by cooleel** [X-PLUG/mPLUG-DocOwl#15]
https://modelscope.cn/studios/damo/mPLUG-DocOwl/summary
This site is down at this moment, it said `当前空间运行错误，暂未发布`

**Comment by HAWLYQ** [comment]
Thanks for your attention, we will re-launch the demo by the end of this moth.

**Comment by HAWLYQ** [comment]
> Thanks for fixing it. It seems the only way to log into this website is through a Chinese phone number ?
Hi @cooleel , our demo is now available on both huggingface and modelscope~
