### ISSUE TITLE
能不能把mpaper数据集传到modelscope上

### ISSUE THREAD

**Issue by John-Ge** [X-PLUG/mPLUG-DocOwl#17]
从hf下载太慢了，求在modelscope上传一份

**Comment by HAWLYQ** [comment]
好的，我们近期会在modelscope上传一份～

**Comment by tjtanaa** [comment]
https://huggingface.co/datasets/mPLUG/M-Paper/tree/main
請問這些partial-image檔案怎麽開？

**Comment by HAWLYQ** [comment]
cat partial-imgs* > imgs.tar.gz
tar -zxvf imgs.tar.gz

**Comment by HAWLYQ** [comment]
> https://huggingface.co/datasets/mPLUG/M-Paper/tree/main
> 請問這些partial-image檔案怎麽開？

cat partial-imgs* > imgs.tar.gz
tar -zxvf imgs.tar.gz

**Comment by HAWLYQ** [comment]
> 非常感谢！

M-Paper已传到ModelScope (https://www.modelscope.cn/datasets/iic/M-Paper)
