### ISSUE TITLE
modelscope在线测试效果较差？

### ISSUE THREAD

**Issue by ATP-BME** [X-PLUG/mPLUG-DocOwl#18]
![image](https://github.com/X-PLUG/mPLUG-DocOwl/assets/110229267/1e20d3ed-02ca-4513-bad3-219ccd44ec07)
如图，在modelscope进行在线测试，模型无法完成文本抽取任务

**Comment by HAWLYQ** [comment]
感谢您的关注！
1. docowl系列目前是纯英文模型，中英双语模型开发中；
2. 目前modelscope上的demo仍然是docowl 1.0，docowl 1.5还未上线，我们预计在下周进行陆续的开源。
