### ISSUE TITLE
About DocStruct4M and DocReason25K

### ISSUE THREAD

**Issue by SWHL** [X-PLUG/mPLUG-DocOwl#19]
Thanks for your great work! 

In the paper: **mPLUG-DocOwl 1.5: Unified Structure Learning for OCR-free Document Understanding**, it mentioned DocStruct4M and DocReason25K dataset, but they are not open-source.

May I ask if there are any open source plans for these two datasets?

**Comment by HAWLYQ** [comment]
Thanks for your attention~ these two datasets are planned to be open-source in next week!

**Comment by SWHL** [comment]
wow, thanks
