### ISSUE TITLE
Instruction following data

### ISSUE THREAD

**Issue by ChrisLiu6** [X-PLUG/mPLUG-DocOwl#2]
Hi! Thank you for the excellent work!

The unified instruction tuning dataset is a great contribution to the community and can be very useful. I wonder if there is a timetable for its release? Thanks!

**Comment by LukeForeverYoung** [comment]
Thank you for your interest in our work. We plan to release the instruction data and source code together. However, we do not have an exact release date as there are some ongoing research works that are still unfinished. 

The instruction data we used were collected from public sources. Alternatively, you may also collect them yourself.
