### ISSUE TITLE
Missing Images for Paperowl

### ISSUE THREAD

**Issue by BajajSmriti** [X-PLUG/mPLUG-DocOwl#20]
I have tried to execute the steps as enlisted [here](https://github.com/X-PLUG/mPLUG-DocOwl/tree/main/PaperOwl#m-paper) for extracting the PaperOwl dataset. Can you please confirm if these images are really missing or is there something wrong in extraction?

imgs/2106.08905v2/figures/out_28170.png
imgs/2106.08905v2/figures/28170.png
imgs/2303.16501v1/tables/table_7.png
imgs/2305.16835v1/figures/fig_result_2.png
imgs/2102.12037v3/figures/table-AUROC-boed.png
imgs/1908.09231v1/tables/table_1.png
.... more images are missing

**Comment by HAWLYQ** [comment]
Hi, @BajajSmriti , I have checked these images are contained in the ./imgs directory. Please check you have downloaded all partial-imgs files, the 'cat' and 'tar -zxvf'  can also run without errors when the lase partial-imgs file is missing.
