### ISSUE TITLE
数据集下载问题

### ISSUE THREAD

**Issue by mactavish91** [X-PLUG/mPLUG-DocOwl#22]
请问mPLUG-DocOwl 1.5的数据集在huggingface上的链接失效是什么原因

**Comment by HAWLYQ** [comment]
Hi, @mactavish91 ，因为项目还处于公司内部审查状态，所以数据仍然是private，很快会变成public

**Comment by HAWLYQ** [comment]
Hi, @mactavish91 , datasets have been changed to public, please try again
