### ISSUE TITLE
DocOwl 1.5 model links not working

### ISSUE THREAD

**Issue by MayStepanyan** [X-PLUG/mPLUG-DocOwl#23]
I found links to HF model cards in DocOwl 1.5 [README](https://github.com/X-PLUG/mPLUG-DocOwl/tree/main/DocOwl1.5), but none of them works. 

 Also, I found no models here https://huggingface.co/mPLUG
 
 Can you please provide working links?

**Comment by HAWLYQ** [comment]
Hi @MayStepanyan , the link is still 'private,' it will be changed to 'public' soon.

**Comment by HAWLYQ** [comment]
Hi, @MayStepanyan ,the link has been changed to 'public', please try again~
