### ISSUE TITLE
instruction with how to use the stage1 model

### ISSUE THREAD

**Issue by yongkangzhao** [X-PLUG/mPLUG-DocOwl#24]
Hi team, 

Is there any instruction on how to use the stage1 model? interested with the document/webpage parsing capabilities.
If not can you provide an example script?

Thanks!!

**Comment by HAWLYQ** [comment]
Hi, @yongkangzhao , we have provided inference examples in the [README.md](https://github.com/X-PLUG/mPLUG-DocOwl/blob/main/DocOwl1.5/README.md). 
You can find more templates in the struct_aware_parse.jsonl file of [mPLUG/DocStruct4M](https://huggingface.co/datasets/mPLUG/DocStruct4M/).

**Comment by yongkangzhao** [comment]
awesome!!!

Thank you, I got it working!
