### ISSUE TITLE
complex figures

### ISSUE THREAD

**Issue by flckv** [X-PLUG/mPLUG-DocOwl#27]
great work. What is the best way to extract complex figures from pdfs? is there a way to parse them as images and then apply ocr (worst case) or?

I noticed that complex figures are not translated:  
see from your paper:
![image](https://github.com/X-PLUG/mPLUG-DocOwl/assets/103381497/8d7532bc-c23b-46be-8cda-810f8a4e9ce5)
![Pasted Graphic 2](https://github.com/X-PLUG/mPLUG-DocOwl/assets/103381497/bfd12309-178a-46bb-8210-4a379fb9602e)

**Comment by HAWLYQ** [comment]
Hi, @flckv , most training samples of document parsing are constructed with [pdfplumber](https://github.com/jsvine/pdfplumber), which tends to ignore images in PDFs to keep the semantic consistency of the text content. Thus, our model may also sometimes ignore texts in the figures. An alternative way is to extract the image from the pdf and then perform parsing or instruct the model with a bounding box like the format of Multi-grained Text grounding.

**Comment by flckv** [comment]
@HAWLYQ thank you.
