### ISSUE TITLE
What is the difference between DocDownstrem1.0 and the finetuned data used in UReader

### ISSUE THREAD

**Issue by FaltingsA** [X-PLUG/mPLUG-DocOwl#28]
Thanks for your great work！ What is the difference between DocDownstrem1.0 and the finetund data used in Ureader？

**Comment by HAWLYQ** [comment]
Hi @FaltingsA ,the main difference is the text reading samples used in UReader are removed from DocDownstream1.0, because we have perform strict-aware parsing learning in the first stage.

**Comment by FaltingsA** [comment]
Thanks!
