### ISSUE TITLE
关于patch_positions的疑问

### ISSUE THREAD

**Issue by whalefa1I** [X-PLUG/mPLUG-DocOwl#29]
https://github.com/X-PLUG/mPLUG-DocOwl/blob/ebe8ac76cd7477f4faf5a4a44ac3eae027a21e66/DocOwl1.5/mplug_docowl/model/modeling_mplug_docowl.py#L59

请问patch_positions没有被使用吗？

**Comment by HAWLYQ** [comment]
是的，正如论文里提到的，docowl1.5摒弃了需要学习的切图位置编码，采用文本token表示切图所在行列，所以patch position不再需要了。
