### ISSUE TITLE
online demo performance is not so good, if latest one has been updated

### ISSUE THREAD

**Issue by charliedream1** [X-PLUG/mPLUG-DocOwl#31]
- online demo always gives very short answer
- extract text also wrong
- gives messy text output

**Comment by HAWLYQ** [comment]
Hi, @charliedream1 , the demo is still based on DocOwl, the demo of DocOwl 1.5 is under development and will be release within a week!

**Comment by charliedream1** [comment]
what about model weight on modelscope and code, is that the latest and possible to reproduce latest performance with these on local machine?

**Comment by HAWLYQ** [comment]
> what about model weight on modelscope and code, is that the latest and possible to reproduce latest performance with these on local machine?

Yes, you can try parsing texts with DocOwl-stage1 and detailed explanations with DocOwl-Chat.

**Comment by charliedream1** [comment]
Okay, thx, i'll try



---Original---
From: "Anwen ***@***.***&gt;
Date: Tue, Apr 2, 2024 16:15 PM
To: ***@***.***&gt;;
Cc: "Optimus ***@***.******@***.***&gt;;
Subject: Re: [X-PLUG/mPLUG-DocOwl] online demo performance is not so good, iflatest one has been updated (Issue #31)




  
what about model weight on modelscope and code, is that the latest and possible to reproduce latest performance with these on local machine?
  
Yes, you can try parsing texts with DocOwl-stage1 and detailed explanations with DocOwl-Chat.
