### ISSUE TITLE
DocOwl1.5 按示例代码运行 推理结果仅仅重复部分文字。

### ISSUE THREAD

**Issue by BeyondLightYear** [X-PLUG/mPLUG-DocOwl#32]
DocOwl1.5 按示例代码运行：识别图片中的文字。 推理结果仅仅重复部分文字。并在运行代码后 出现提示'...Setting `pad_token_id` to `eos_token_id`:2 for open-end generation....'
![屏幕截图 2024-04-02 155430](https://github.com/X-PLUG/mPLUG-DocOwl/assets/52820978/40d97062-c5b4-4ef8-b275-db338b96cf3c)

**Comment by HAWLYQ** [comment]
Hi, @BeyondLightYear, 目前DocOwl只支持英文，所以中文大概率会输出异常，我们的中英版本正在开发中。

**Comment by weixiewen** [comment]
> Hi, @BeyondLightYear, 目前DocOwl只支持英文，所以中文大概率会输出异常，我们的中英版本正在开发中。

非常棒的项目，想问一下中文有排版什么时候发布么？

**Comment by HAWLYQ** [comment]
@weixiewen ，您好，感谢关注～由于资源紧张（近期发布了TinyChart-3B），我们中英版本的发布计划在五月中旬~

**Comment by limaopeng1** [comment]
> @weixiewen ，您好，感谢关注～由于资源紧张（近期发布了TinyChart-3B），我们中英版本的发布计划在五月中旬~

请问下中英版本TinyChart的发步计划是？
