### ISSUE TITLE
Spelling errors in DocStruct4M, 'multi_grained_text_localization.jsonl'

### ISSUE THREAD

**Issue by chrysanthemum-515** [X-PLUG/mPLUG-DocOwl#34]
All the question prompts are extracted from DocStruct4M, 'multi_grained_text_localization.jsonl' as below,
```
[
  "Give the bounding box of the text",
  "Predict the bounding box of the text",
  "Detect the text in the bounding box",
  "Identify the text within the bounding box",
  "Recognize the text in the bounding box",
  "Locate the postion of the text"
]
```
In the last column, 'postion' should be replaced with 'position'.
I wonder whether it matters for training the MLLM, because the error amount is significantly high.

**Comment by HAWLYQ** [comment]
Hi, @chrysanthemum-515 Thanks a lot for your careful check and kind reminder. I think this minor error will not significantly influence the model due to the strong language understanding ability of LLM. If you feel risky, you can revise this spelling error for model training and evaluation.

**Comment by chrysanthemum-515** [comment]
> Hi, @chrysanthemum-515 Thanks a lot for your careful check and kind reminder. I think this minor error will not significantly influence the model due to the strong language understanding ability of LLM. If you feel risky, you can revise this spelling error for model training and evaluation.

Thanks for reply.
