### ISSUE TITLE
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an  `offload_folder` for them and RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by tesla150600** [X-PLUG/mPLUG-DocOwl#35]

**Comment by tesla150600** [comment]
When I try to run the Quick Start Code instruction in Google сolab, I get the following error 
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them.
after adding offload_folder="offload", offload_state_dict = True, to repair its article  https://huggingface.co/blog/accelerate-large-models,
I get a new error which I can not fix 
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
Also i have always this message
Some weights of MPLUGOwl2LlamaForCausalLM were not initialized from the model checkpoint at MAGAer13/mplug-owl2-llama2-7b and are newly initialized: ['model.visual_abstractor.encoder.layers.1.crossattention.attention.q_pos_embed', 'model.visual_abstractor.encoder.layers.4.crossattention.attention.q_pos_embed', 'model.visual_abstractor.encoder.layers.2.crossattention.attention.q_pos_embed', 'model.visual_abstractor.encoder.layers.3.crossattention.attention.q_pos_embed', 'model.visual_abstractor.encoder.layers.0.crossattention.attention.q_pos_embed', 'model.visual_abstractor.encoder.layers.5.crossattention.attention.q_pos_embed', 'model.visual_abstractor.encoder.layers.1.crossattention.attention.k_pos_embed', 'model.visual_abstractor.encoder.layers.4.crossattention.attention.k_pos_embed', 'model.visual_abstractor.encoder.layers.2.crossattention.attention.k_pos_embed', 'model.visual_abstractor.encoder.layers.5.crossattention.attention.k_pos_embed', 'model.visual_abstractor.encoder.layers.3.crossattention.attention.k_pos_embed', 'model.visual_abstractor.encoder.layers.0.crossattention.attention.k_pos_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Please help me figure out

**Comment by HAWLYQ** [comment]
@tesla150600 sorry, I am not familiar with Google сolab, but it seems you are loading mPLUG-Owl2 rather than DocOwl1.5.

**Comment by tesla150600** [comment]
Yes, you're right, I ran the wrong code, but when I run the code from the DocOwl1.5-stage1, I will get a new error, maybe this is a problem with library versions?
![зображення](https://github.com/X-PLUG/mPLUG-DocOwl/assets/45979299/8834999a-2ad8-4179-9129-b4a5a090aefa)

**Comment by HAWLYQ** [comment]
> code

try transformers == 4.31.0

**Comment by HAWLYQ** [comment]
> Yes, you're right, I ran the wrong code, but when I run the code from the DocOwl1.5-stage1, I will get a new error, maybe this is a problem with library versions? ![зображення](https://private-user-images.githubusercontent.com/45979299/319155396-8834999a-2ad8-4179-9129-b4a5a090aefa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDI1NzEsIm5iZiI6MTcxMjE0MjI3MSwicGF0aCI6Ii80NTk3OTI5OS8zMTkxNTUzOTYtODgzNDk5OWEtMmFkOC00MTc5LTkxMjktYjRhNWEwOTBhZWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDExMDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwM2M5MjZkZjQyZDEwN2Y1Y2ZlNzIyM2ZjMDQxMDAyOWQxNzRjYmVmMTA4NGFlNDRiMmNhYzYwMTY1YWIxOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FydPGToehuQ6eAjDBDy_zfuLfMOd4ESWfzaM1maXND0)

try transformers == 4.31.0

**Comment by tesla150600** [comment]
Yes, it worked, thank you very much for your help,
But then the code flew out due to a lack of GPU RAM, so how much GPU RAM does it take for the model to work?
and also thanks for the quick answers

**Comment by HAWLYQ** [comment]
> Yes, it worked, thank you very much for your help, But then the code flew out due to a lack of GPU RAM, so how much GPU RAM does it take for the model to work? and also thanks for the quick answers

We have verified that the inference code can be run with a V100-32G.

**Comment by tesla150600** [comment]
Thanks a lot
