### ISSUE TITLE
Online demo parameters

### ISSUE THREAD

**Issue by MayStepanyan** [X-PLUG/mPLUG-DocOwl#37]
I'd like to get the same results with `Omni` model as demonstrated in [huggingface demo ](https://huggingface.co/spaces/mPLUG/DocOwl)using the inference code in this repo. 

Could you share what parameters like anchor/grid, input resolution etc. you use under the hood? Is there any other pre- or postprocessing for the query or the input image that is absent from the inference code? 

For example, with an image that says:

```
MAKE TEXT
STAND OUT FROM 
BACKGROUNDS
```
I've got the following results:

With inference code:

```
from docowl_infer import DocOwlInfer

model_path = 'mPLUG/DocOwl1.5-Omni'
docowl=DocOwlInfer(ckpt_path=model_path, anchors='grid_9', add_global_img=True)
query = "Parse texts in the image."
answer = docowl.inference(image_path, query)
```

Output:

```
<doc>     MAKE TEXT FROM IEX 
    STAOKOROUNDLICKGRIUINI </doc>
```
While the demo gives outputs:

```
[doc] TEXT MAKE
STAND OUT FROM
BACKGROUNDS [/doc]
```

EDIT: Added example

**Comment by HAWLYQ** [comment]
Hi, @MayStepanyan there are no parameter differences between online demo and inference code. However, I found that the web code (gradio) of the demo will resize the input image. For example, an 1890x1352 image will be resized to 559x400 before being fed to the model. This may influence the prediction.

**Comment by MayStepanyan** [comment]
@HAWLYQ thanks for your prompt response. 

Could you please specify the `DocOwlInfer` instance arguments from the demo too, specifically:

- `anchors`
- `add_global_img`

Also, it seems that `model.generate` from the demo uses sampling, while the inference script clearly doesn't (do_sample is set to False`. If not, whats the top P from the left toolbar in the demo? Could you clarify this too?

Thanks.

**Comment by HAWLYQ** [comment]
@MayStepanyan ，for online demo，ahchors is grid_9 and add_global_image is true. Actually，the sample and top p are not used in our demo，you can find details in the files of our hf space

**Comment by MayStepanyan** [comment]
Thanks!
