### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by zhuzizyf** [X-PLUG/mPLUG-DocOwl#39]
When start supporting Chinese document Q&A?

**Comment by HAWLYQ** [comment]
> When start supporting Chinese document Q&A?

Hi，chinese model is still under development，which is scheduled for release within this month～

**Comment by nhsjgczryf** [comment]
> > 什么时候开始支持中文文档问答？
> 
> Hi，中文版还在开发中，预计本月内发布～

嗨，请问中文版会开源数据吗？

**Comment by HAWLYQ** [comment]
> > > 什么时候开始支持中文文档问答？
> > 
> > 
> > Hi，中文版还在开发中，预计本月内发布～
> 
> 嗨，请问中文版会开源数据吗？

我们模型正在开发中，如果效果不错会考虑开源数据～
