### ISSUE TITLE
There is an error in HReducer-Module Code comments

### ISSUE THREAD

**Issue by SuXuping** [X-PLUG/mPLUG-DocOwl#41]
MplugDocOwlHReducerModel --> forward --> line 487
sequence_output = self.reducer(hidden_states) # B,C,H,W -> B,C,H/conv_shape[1],W/(conv_shape[1])
After self.reducer operation, the shape of hidden_states should be (B,C,H/conv_shape[0],W/(conv_shape[1])).

**Comment by HAWLYQ** [comment]
Hi, @SuXuping  Thanks for pointing out this typo error in the comments~ We have fixed it~
