### ISSUE TITLE
Question about <bbox> in DocDownstream dataset 

### ISSUE THREAD

**Issue by niiickZ** [X-PLUG/mPLUG-DocOwl#45]
The meaning of the values in < bbox > are confusing. It doesn't look in the format of x1,y1,x2,y2, since it failes to get correct bbox for most images.

**Comment by HAWLYQ** [comment]
Hi, @niiickZ <bbox> just exists in Multi-grained Text Localization tasks in DocStruct4M. There shouldn't be <bbox> in DocDownstream-1.0. Besides, each value  x in <bbox> is not the absolute position in the image。 The x/999 is the normalized position in the image.

**Comment by niiickZ** [comment]
Thanks for answering, it works.  And indeed it only exists in DocStruct4M, sorry for my typo.
