### ISSUE TITLE
How to get the real bbox and questions about the normalization function

### ISSUE THREAD

**Issue by HanielF** [X-PLUG/mPLUG-DocOwl#49]
Both  Multi-grained Text Grounding and Multi-grained Text Recognition task need bounding box to get the correspondence between specific texts and local positions. 
The bbox in DocLocal4K and DocStruct4M datasets seems not real bounding box of the imgs.

My question is
1. how to get the real image bounding box of the image? 
2. the normalized function, `max(min(int(x)/999, 1.0), 0.0) for x in gt_answer.split(',')]`,  will truncate the relatively large coordinates to 1. Isn't there a problem with this?

**Comment by HAWLYQ** [comment]
Hi, @HanielF, 
1. for each bbox <x1, y1, x2, y2> in these two tasks, you can get the normalized bbox by <x1/999, y1/999, x2/999, y2/999>. 
2. Truncating the relatively large coordinates to 1. is to ensure the predicted bbox within the image.

**Comment by HanielF** [comment]
Thanks for your reply.
I still want to know how the normalization coordinates correspond to the actual coordinates when model inference. In some case, such as drawing a bbox box during visualization will use the real bbox to match the text in image.

**Comment by HAWLYQ** [comment]
> @HAWLYQ Thanks for your reply. I still want to know how the normalization coordinates correspond to the actual coordinates when model inference. In some case, such as drawing a bbox box during visualization will use the real bbox to match the text in image.

multiply the normalized bbox with the image size.

**Comment by HanielF** [comment]
> > @HAWLYQ Thanks for your reply. I still want to know how the normalization coordinates correspond to the actual coordinates when model inference. In some case, such as drawing a bbox box during visualization will use the real bbox to match the text in image.
> 
> multiply the normalized bbox with the image size,`<x1/999 x W, y1/999 x H, x2/999 x W, y2/999 x H>`

Thank you very much.
