### ISSUE TITLE
 bilingual plan

### ISSUE THREAD

**Issue by bei612** [X-PLUG/mPLUG-DocOwl#53]
Could you please tell any advance insight into the timeline for the bilingual model ( en & zh )?
Will there be significant changes to the existing overall technical architecture for new bilingual model?
Which LLM will be considered for the decoder part?

**Comment by HAWLYQ** [comment]
Hi, @bei612 we plan to release the bilingual model at the end of this month. There will not be significant changes to the overall architecture. The model details will be reported at the same time~
