### ISSUE TITLE
Official links of TextVQA and TextCaps.

### ISSUE THREAD

**Issue by niiickZ** [X-PLUG/mPLUG-DocOwl#54]
Thanks for your great work. 
I can not find where to submit for evaluating TextVQA and TextCaps. The challenge seems has finished. Can you please provide the official link for submission?

**Comment by HAWLYQ** [comment]
Hi, @niiickZ although these two challenges have finished, you can still evaluate your results of test sets on 
https://eval.ai/web/challenges/challenge-page/906/submission and https://eval.ai/web/challenges/challenge-page/874/submission. Either Test-Standard or Test-Violating-Standard-Guidelines phrase is OK.

**Comment by niiickZ** [comment]
Thanks
