### ISSUE TITLE
Question about multi pages/images

### ISSUE THREAD

**Issue by sky-fly97** [X-PLUG/mPLUG-DocOwl#58]
Could you tell me which model in this series can support multiple-page inputs?

**Comment by HAWLYQ** [comment]
Hi, @sky-fly97 , our models are currently not finetuned or evaluated with multi-page samples. Honestly, we're not quite sure whether these models could handle multi-page input.  You can try inference with our [docowl1.5](https://github.com/X-PLUG/mPLUG-DocOwl/tree/main/DocOwl1.5) model.

**Comment by sky-fly97** [comment]
Thanks, I will try. By the way, it seems that there are very few models on the market that can handle multi-graph input, and only Qwen-vl-chat and GPT4V have been seen so far.

**Comment by HAWLYQ** [comment]
> Thanks, I will try. By the way, it seems that there are very few models on the market that can handle multi-page input, I've only seen qwen-vl-chat and GPT4V so far.

Yes，three is still a lack of effective open-source methods for multi-image understanding.
