### ISSUE TITLE
Tiny Chart inference code not available

### ISSUE THREAD

**Issue by ViCtOr-dev13** [X-PLUG/mPLUG-DocOwl#62]
Hello, I'm trying to figure out how to use the tinychart model, and inference.ipynb is not available, I have a 404 error not found.
Help please

**Comment by zhangliang-04** [comment]
Hi @ViCtOr-dev13,
It seems that `inference.ipynb` is accidentally ignored by `.gitignore`. Now you can find it at [here](https://github.com/X-PLUG/mPLUG-DocOwl/blob/main/TinyChart/inference.ipynb). 
Have fun!

**Comment by ViCtOr-dev13** [comment]
thanks a lot @zhangliang-04
