### ISSUE TITLE
Try to run sigclip model 

### ISSUE THREAD

**Issue by ViCtOr-dev13** [X-PLUG/mPLUG-DocOwl#63]
hello everyone , I 'm  trying to run the tinychart sgclip model but I'm facing issues with this code : 
`model_path = "mPLUG/TinyChart-3B-768-siglip"

tokenizer, model, image_processor, context_len = load_pretrained_model(
    model_path, 
    model_base=None,
    model_name=get_model_name_from_path(model_path),
    device="cuda"
)`
I have an error because it can't find tokenizer I suppose. 
![image](https://github.com/X-PLUG/mPLUG-DocOwl/assets/60699144/4d630e30-b75e-463f-8e43-f43c269ac413)
help me please.

**Comment by zhangliang-04** [comment]
Hi @ViCtOr-dev13,
`mPLUG/TinyChart-3B-768-siglip` is the vision encoder of `mPLUG/TinyChart-3B-768` and it cannot be deployed separately. If your purpose is chart understanding, please try to load `mPLUG/TinyChart-3B-768`. It will load `mPLUG/TinyChart-3B-768-siglip` from huggingface hub automatically by default. 

By the way, if you want to load the vision transformer locally, try to set `mm_vision_tower` in `config.json` of  `TinyChart-3B-768` to the local path of `mPLUG/TinyChart-3B-768-siglip`.

**Comment by ViCtOr-dev13** [comment]
thanks a lot
