### ISSUE TITLE
 M-Paper data

### ISSUE THREAD

**Issue by limitedfxw** [X-PLUG/mPLUG-DocOwl#64]
请问[M-Paper]的原始pdf数据可以提供下吗

**Comment by HAWLYQ** [comment]
Hi, @limitedfxw 我们暂时没有整理开源原始pdf的计划～通过论文id，你可以很方便地下载到原始pdf，比如 ```wget https://arxiv.org/pdf/2403.12895v1 -O ./2403.12895v1.pdf```
