### ISSUE TITLE
Huggingface integration

### ISSUE THREAD

**Issue by temiwale88** [X-PLUG/mPLUG-DocOwl#7]
Thank you for your work!
When will you make this available on Huggingface with instructions please?

Thanks.

**Comment by matankley** [comment]
+1

**Comment by doreilly257** [comment]
+1

**Comment by HAWLYQ** [comment]
1. The weights  and training data of UReader have been released on Huggingface, see [UReader](https://github.com/X-PLUG/mPLUG-DocOwl/tree/main/UReader)
2. Open-sourcing the Docowl 1.5 on Huggingface is scheduled for next week.

**Comment by temiwale88** [comment]
> 1. The weights  and training data of UReader have been released on Huggingface, see [UReader](https://github.com/X-PLUG/mPLUG-DocOwl/tree/main/UReader)
> 2. Open-sourcing the Docowl 1.5 on Huggingface is scheduled for next week.

Thanks @HAWLYQ . please let us know once it's on huggingface. Thank you for your work!

**Comment by HAWLYQ** [comment]
Hi, @temiwale88 , our datasets, models and demo are on huggingface now

**Comment by temiwale88** [comment]
@HAWLYQ  - thank you! I suspect the models are found here - [https://huggingface.co/mPLUG](https://huggingface.co/mPLUG)
Any documentation on how to use e.g. **Model Card**?

**Comment by HAWLYQ** [comment]
> @HAWLYQ - thank you! I suspect the models are found here - https://huggingface.co/mPLUG Any documentation on how to use e.g. **Model Card**?
> 
> Thanks again!

you can find model usage in [DcoOwl1.5](https://github.com/X-PLUG/mPLUG-DocOwl/tree/main/DocOwl1.5)

**Comment by temiwale88** [comment]
Sigh - this is incredible! Thank you so much! I assume this is under Apache license?
Kindly close this 'issue'. It's resolved for me. **Thank you!**
