### ISSUE TITLE
About dataset when train model

### ISSUE THREAD

**Issue by SWHL** [X-PLUG/mPLUG-DocOwl#77]
Hello, thank you for your excellent work.

I am curious about the identifiers `<doc></doc>`, `<ocr></ocr>`, `<md></md>` etc. introduced in the DocStruct4M dataset to unify various tasks. I did not see any special treatment for them in the training code, and they did not appear as special tokens.

I would like to ask, during training, are these introduced identifiers treated as normal text? Or are there other processing techniques?

Thank you.

**Comment by HAWLYQ** [comment]
Hi @SWHL, there is no special treatment for such identifiers. They are treated as normal text and just used to distinguish texts parsed from images with normal answers given by the LLM.

**Comment by SWHL** [comment]
Thanks for your reponse. It's very clear.

I have another question about DocDownStream1.0, which does not appear in the paper.
Where is the dataset used?

**Comment by HAWLYQ** [comment]
Hi @SWHL, DocDownStream1.0 is used in 2nd-stage training~

**Comment by SWHL** [comment]
Thanks for your reponse so fast.

**Comment by SWHL** [comment]
Hello, when I read the DocOwl1.5 paper, I meet another question about the special token.
In the Table Parsing part of the paper, it writes **you add special text tokens**:
![image](https://github.com/X-PLUG/mPLUG-DocOwl/assets/28639377/a96ac241-43a7-45d9-8bca-35b8c285b147)

But I couldn't find the special token in the [DocOwl 1.5 tokenizer's vocab](https://huggingface.co/mPLUG/DocOwl1.5-stage1/blob/main/special_tokens_map.json):
```json
{
  "bos_token": {
    "content": "<s>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  },
  "eos_token": {
    "content": "</s>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  },
  "pad_token": "<unk>",
  "unk_token": {
    "content": "<unk>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  }
}
```

And at the same time, I couldn't find related code in the repo source code.

So how do the `colspan` and `rowspan` server as special token?
Thank you very much.

**Comment by HAWLYQ** [comment]
> Hello, when I read the DocOwl1.5 paper, I meet another question about the special token. In the Table Parsing part of the paper, it writes **you add special text tokens**: ![image](https://private-user-images.githubusercontent.com/28639377/340902708-a96ac241-43a7-45d9-8bca-35b8c285b147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjkzMzMsIm5iZiI6MTcxODc2OTAzMywicGF0aCI6Ii8yODYzOTM3Ny8zNDA5MDI3MDgtYTk2YWMyNDEtNDNhNy00NWQ5LThiY2EtMzViOGMyODViMTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAzNTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OGVjNWNmYmY1ZjM5ZGUzZmZkMmYxMDI2NTI0ODdiZWNlNjhiYzk5MWVmM2U4YzZjNTUyNzg1ZWIwZTI1MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kfqosm5QK8TWkYNHfzkkwXB4L3LPBY7UmD6xyj8V1aA)
> 
> But I couldn't find the special token in the [DocOwl 1.5 tokenizer's vocab](https://huggingface.co/mPLUG/DocOwl1.5-stage1/blob/main/special_tokens_map.json):
> 
> ```json
> {
>   "bos_token": {
>     "content": "<s>",
>     "lstrip": false,
>     "normalized": false,
>     "rstrip": false,
>     "single_word": false
>   },
>   "eos_token": {
>     "content": "</s>",
>     "lstrip": false,
>     "normalized": false,
>     "rstrip": false,
>     "single_word": false
>   },
>   "pad_token": "<unk>",
>   "unk_token": {
>     "content": "<unk>",
>     "lstrip": false,
>     "normalized": false,
>     "rstrip": false,
>     "single_word": false
>   }
> }
> ```
> 
> And at the same time, I couldn't find related code in the repo source code.
> 
> So how do the `colspan` and `rowspan` server as special token? Thank you very much.

Hi, the 'special token' doesn't mean adding to the token file, just ditinguishing tokens to indicate row/column span, they are treated as normal texts~

**Comment by SWHL** [comment]
Thanks.
