### ISSUE TITLE
About the data preprocess

### ISSUE THREAD

**Issue by Coobiw** [X-PLUG/mPLUG-DocOwl#8]
Thanks for your great job! I'm really curious about the pre-process of the dataset. So I'd like to ask you about the following:
1. Such as DocVQA, one question may have several answers. How did you process it? Sampling? Or re-organize dataset per answer?
2. What is the resolution of the input image?
3. How did you process the datasets with multi-page pdf(such as KLC/DeppForm)

Thanks for your reply!

**Comment by HAWLYQ** [comment]
Hi @Coobiw ,
1. for each question of DocVQA, we sample an answer as the target during training. (the evaluation follows the DUE-Benchmark)
2. The resolution of the input image is not fixed. You can check this by downloading our dataset [DocDownstream-1.0](https://huggingface.co/datasets/mPLUG/DocDownstream-1.0).
3. For multi-page datasets, we've only used the first page as input so far.
