### ISSUE TITLE
FineTune TinyChart

### ISSUE THREAD

**Issue by LilDevsy0117** [X-PLUG/mPLUG-DocOwl#88]
Hi

![image](https://github.com/X-PLUG/mPLUG-DocOwl/assets/80056110/bfaad91c-31dc-41ec-b562-b86b2d3d136c)

  
How can I solve this error?

**Comment by zhangliang-04** [comment]
Did you use multiple GPUs in this run? It seems that the real error was not displayed.

**Comment by LilDevsy0117** [comment]
Increased the memory to 128GB and solved it. Thank you.
