### ISSUE TITLE
What is the crop_anchor argument?

### ISSUE THREAD

**Issue by Mihaiii** [X-PLUG/mPLUG-DocOwl#97]
Hi!

I'd like to fine-tune your model, but it's not clear to me what the [crop_anchor argument](https://github.com/X-PLUG/mPLUG-DocOwl/blob/758c3cb5e59cafbde6b422e7cebfc9244a50d1f3/DocOwl1.5/scripts/finetune_docowl_lora.sh#L34) is for and if I need to update/mark my document images in any way before processing.

Please update the documentation with this information - it's not clear what the default (grid_9) value means.

Thank you!

**Comment by HAWLYQ** [comment]
Hi, @Mihaiii , the crop_anchor is the argument about the max crop number of an input image, and the grid_9 means an image can be cropped into a max of 9 sub-images (each 448x488), depending on its raw resolution.

**Comment by Mihaiii** [comment]
Thank you for the explanation!
